// <auto-generated />
using System;
using GimnasioFacil.App.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GimnasioFacil.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20220829210257_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("GimnasioFacil.App.Dominio.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraseña")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("GimnasioFacil.App.Dominio.Entrenamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ValoracionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ValoracionId");

                    b.ToTable("Entrenamientos");
                });

            modelBuilder.Entity("GimnasioFacil.App.Dominio.Nutricion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EntrenamientoId")
                        .HasColumnType("int");

                    b.Property<string>("NombreNutricion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EntrenamientoId");

                    b.ToTable("Nutriciones");
                });

            modelBuilder.Entity("GimnasioFacil.App.Dominio.Rutina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EntrenamientoId")
                        .HasColumnType("int");

                    b.Property<string>("NombreRutina")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EntrenamientoId");

                    b.ToTable("Rutinas");
                });

            modelBuilder.Entity("GimnasioFacil.App.Dominio.Valoracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<float>("Altura")
                        .HasColumnType("real");

                    b.Property<string>("Edad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Peso")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Valoraciones");
                });

            modelBuilder.Entity("GimnasioFacil.App.Dominio.Entrenamiento", b =>
                {
                    b.HasOne("GimnasioFacil.App.Dominio.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("GimnasioFacil.App.Dominio.Valoracion", "Valoracion")
                        .WithMany()
                        .HasForeignKey("ValoracionId");

                    b.Navigation("Cliente");

                    b.Navigation("Valoracion");
                });

            modelBuilder.Entity("GimnasioFacil.App.Dominio.Nutricion", b =>
                {
                    b.HasOne("GimnasioFacil.App.Dominio.Entrenamiento", null)
                        .WithMany("Nutricion")
                        .HasForeignKey("EntrenamientoId");
                });

            modelBuilder.Entity("GimnasioFacil.App.Dominio.Rutina", b =>
                {
                    b.HasOne("GimnasioFacil.App.Dominio.Entrenamiento", null)
                        .WithMany("Rutina")
                        .HasForeignKey("EntrenamientoId");
                });

            modelBuilder.Entity("GimnasioFacil.App.Dominio.Entrenamiento", b =>
                {
                    b.Navigation("Nutricion");

                    b.Navigation("Rutina");
                });
#pragma warning restore 612, 618
        }
    }
}
